spring:
  application:
    name: human-flavor-cookie
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://human-flavor-cookie-database.cbucsc06webs.us-east-1.rds.amazonaws.com:3306/human-flavor-cookie-database
    username: admin
    password: 223819ko
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
jwt:
  expiration-time: 86400000 # 1 day in milliseconds
  secret-key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
logging:
  level:
    org.springframework.security: DEBUG
