spring:
  application:
    name: human-flavor-cookie
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://172.10.7.47/human_flavor_cookie
    username: root
    password: 223819
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
jwt:
  expiration-time: 86400000 # 1 day in milliseconds
  secret-key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
logging:
  level:
    org.springframework.security: DEBUG
